---

- name: upload file to cisco device
  hosts: cisco
  gather_facts: False
  
  tasks:
    - name: upload the file
      cisco_file_transfer: 
            source_file="/home/damian/ANSIBLE/cisco_logging.txt"
            dest_file=cisco_logging.txt
            overwrite=true
            enable_scp=true
            username={{ username }}
            password={{ password }}
            host={{ host }}
            port={{ port }}

